# coding: utf-8

"""
    Stocks

    <h3>Authentication</h3>                     You need to authenticate to use this API.                     To authenticate click on the \"Authorize\" button and do one of the following steps.<br />                     1. Send your API key in the headers of the request by typing \"Bearer my-key\" on the Bearer authorization scheme.<br />                     2. Send your API key on the \"ApiKey\" query string parameter. To do this type your API key in the Query String authorization scheme.<br />                     Both methods are equally valid. We offer both options so that you can use the method that is easier to use in your application.<br />                     <br />                     <h3>API limits</h3>                     Your API key may be subject to daily/hourly limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)                       2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <h3>Suggestions</h3>                     You don't need to implement the whole API by hand in your programming language of choice.<br />                     Since this API has an OpenAPI specification you can use                      <a href=\"https://github.com/swagger-api/swagger-codegen\" target=\"_blank\">Swagger Generator</a>                      to automatically generate client stubs for more than 30 programming languages.                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>  # noqa: E501

    OpenAPI spec version: v1
    Contact: equibles@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Image(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'size': 'int',
        'extension': 'str',
        'filename': 'str',
        'content_type': 'str',
        'web_path': 'str',
        'web_pathname': 'str',
        'width': 'int',
        'height': 'int'
    }

    attribute_map = {
        'size': 'size',
        'extension': 'extension',
        'filename': 'filename',
        'content_type': 'contentType',
        'web_path': 'webPath',
        'web_pathname': 'webPathname',
        'width': 'width',
        'height': 'height'
    }

    def __init__(self, size=None, extension=None, filename=None, content_type=None, web_path=None, web_pathname=None, width=None, height=None):  # noqa: E501
        """Image - a model defined in Swagger"""  # noqa: E501
        self._size = None
        self._extension = None
        self._filename = None
        self._content_type = None
        self._web_path = None
        self._web_pathname = None
        self._width = None
        self._height = None
        self.discriminator = None
        if size is not None:
            self.size = size
        if extension is not None:
            self.extension = extension
        if filename is not None:
            self.filename = filename
        if content_type is not None:
            self.content_type = content_type
        if web_path is not None:
            self.web_path = web_path
        if web_pathname is not None:
            self.web_pathname = web_pathname
        if width is not None:
            self.width = width
        if height is not None:
            self.height = height

    @property
    def size(self):
        """Gets the size of this Image.  # noqa: E501

        The size of the image in bytes.  # noqa: E501

        :return: The size of this Image.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this Image.

        The size of the image in bytes.  # noqa: E501

        :param size: The size of this Image.  # noqa: E501
        :type: int
        """

        self._size = size

    @property
    def extension(self):
        """Gets the extension of this Image.  # noqa: E501

        The image extension. I.e. png.  # noqa: E501

        :return: The extension of this Image.  # noqa: E501
        :rtype: str
        """
        return self._extension

    @extension.setter
    def extension(self, extension):
        """Sets the extension of this Image.

        The image extension. I.e. png.  # noqa: E501

        :param extension: The extension of this Image.  # noqa: E501
        :type: str
        """

        self._extension = extension

    @property
    def filename(self):
        """Gets the filename of this Image.  # noqa: E501

        The image name.  # noqa: E501

        :return: The filename of this Image.  # noqa: E501
        :rtype: str
        """
        return self._filename

    @filename.setter
    def filename(self, filename):
        """Sets the filename of this Image.

        The image name.  # noqa: E501

        :param filename: The filename of this Image.  # noqa: E501
        :type: str
        """

        self._filename = filename

    @property
    def content_type(self):
        """Gets the content_type of this Image.  # noqa: E501

        The content type. I.e. image/png.  # noqa: E501

        :return: The content_type of this Image.  # noqa: E501
        :rtype: str
        """
        return self._content_type

    @content_type.setter
    def content_type(self, content_type):
        """Sets the content_type of this Image.

        The content type. I.e. image/png.  # noqa: E501

        :param content_type: The content_type of this Image.  # noqa: E501
        :type: str
        """

        self._content_type = content_type

    @property
    def web_path(self):
        """Gets the web_path of this Image.  # noqa: E501

        The url of the folder where the image is stored.  # noqa: E501

        :return: The web_path of this Image.  # noqa: E501
        :rtype: str
        """
        return self._web_path

    @web_path.setter
    def web_path(self, web_path):
        """Sets the web_path of this Image.

        The url of the folder where the image is stored.  # noqa: E501

        :param web_path: The web_path of this Image.  # noqa: E501
        :type: str
        """

        self._web_path = web_path

    @property
    def web_pathname(self):
        """Gets the web_pathname of this Image.  # noqa: E501

        The url where the image stored. You can use this URL to download the image.  # noqa: E501

        :return: The web_pathname of this Image.  # noqa: E501
        :rtype: str
        """
        return self._web_pathname

    @web_pathname.setter
    def web_pathname(self, web_pathname):
        """Sets the web_pathname of this Image.

        The url where the image stored. You can use this URL to download the image.  # noqa: E501

        :param web_pathname: The web_pathname of this Image.  # noqa: E501
        :type: str
        """

        self._web_pathname = web_pathname

    @property
    def width(self):
        """Gets the width of this Image.  # noqa: E501

        The width in pixels of the image.  # noqa: E501

        :return: The width of this Image.  # noqa: E501
        :rtype: int
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this Image.

        The width in pixels of the image.  # noqa: E501

        :param width: The width of this Image.  # noqa: E501
        :type: int
        """

        self._width = width

    @property
    def height(self):
        """Gets the height of this Image.  # noqa: E501

        The height in pixels of the image.  # noqa: E501

        :return: The height of this Image.  # noqa: E501
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this Image.

        The height in pixels of the image.  # noqa: E501

        :param height: The height of this Image.  # noqa: E501
        :type: int
        """

        self._height = height

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Image, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Image):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
